FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./server

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "server.app:app"]
